### ISSUE TITLE
Failed to load the language-nsis package

### ISSUE THREAD

**Issue by nemchik** [idleberg/atom-language-nsis#3]
I'm getting an error message any time I start Atom since attempting to update `language-nsis` today. Here is the error
```
Cannot read property 'scripts' of null in C:\Users\enemchik.KEEFORCE\.atom\packages\language-nsis\package.json
Hide Stack Trace
TypeError: Cannot read property 'scripts' of null
    at normalize (C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.14.3\resources\app.asar\node_modules\normalize-package-data\lib\normalize.js:25:11)
    at PackageManager.module.exports.PackageManager.normalizePackageMetadata (C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.14.3\resources\app.asar\src\package-manager.js:748:16)
    at PackageManager.module.exports.PackageManager.loadPackageMetadata (C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.14.3\resources\app.asar\src\package-manager.js:722:18)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.14.3\resources\app.asar\src\package-manager.js:434:35)
    at C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.14.3\resources\app.asar\src\package-manager.js:412:19
    at Config.module.exports.Config.transact (C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.14.3\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.14.3\resources\app.asar\src\package-manager.js:407:19)
    at C:\Users\enemchik.KEEFORCE\AppData\Local\atom\app-1.14.3\resources\app.asar\src\atom-environment.js:794:28
  at C:\Users\enemchik.KEEFORCE\.atom\packages\language-nsis\package.json:1:1
```

Also in Settings > Packages `language-nsis` has an undefined version, no description, and no author. Clicking on the package fills all of this information out as expected, so currently it seems I have version 5.16.0 installed.

**Comment by idleberg** [comment]
Could this have been an incomplete install? It looks like `package.json` is invalid JSON or empty.

**Comment by nemchik** [comment]
Yeah, I uninstalled and reinstalled and that fixed it. Not sure why it failed during the update, but it seems resolved now.
