### ISSUE TITLE
Failed to activate the language-nsis package

### ISSUE THREAD

**Issue by Grahamvs** [idleberg/atom-language-nsis#5]
[Enter steps to reproduce:]

1. Tried to install language-nsis via Atom package manager - Failed
2. Tried using git to clone (as per instructions) - calling yarn fails with "'node' is not recognized as an internal or external command, operable program or batch file."
3. Startup Atom and get the following error

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [language-nsis](https://github.com/idleberg/atom-language-nsis) package 6.17.0

### Stack Trace

Failed to activate the language-nsis package

```
At Cannot find module 'atom-select-list'

Error: Cannot find module 'atom-select-list'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.29.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.29.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/language-nsis/lib/lookup.coffee:1:18)
    at /packages/language-nsis/lib/lookup.coffee:1:1)
    at /packages/language-nsis/lib/lookup.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.29.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.29.0/resources/app/src/native-compile-cache.js:66:33)
    at Object.activate (/packages/language-nsis/lib/main.coffee:85:14)
    at Package.activateNow (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:230:33)
    at measure (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:206:33)
    at Package.measure (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:88:25)
    at activationPromise.Promise (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:200:20)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.29.0/resources/app/src/package.js:198:38)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.29.0/resources/app/src/package-manager.js:695:42)
    at config.transactAsync (~/AppData/Local/atom/app-1.29.0/resources/app/src/package-manager.js:670:36)
    at Config.transactAsync (~/AppData/Local/atom/app-1.29.0/resources/app/src/config.js:866:28)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.29.0/resources/app/src/package-manager.js:668:23)
    at PackageManager.activate (~/AppData/Local/atom/app-1.29.0/resources/app/src/package-manager.js:647:50)
    at loadStatePromise.loadState.then (~/AppData/Local/atom/app-1.29.0/resources/app/src/atom-environment.js:871:27)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-yarn 0.9.0 
duplicate-line-or-selection 0.9.0 
gitkraken-glo 1.0.1 
language-nsis 6.17.0 
simple-drag-drop-text 0.4.0 
tree-view-git-status 1.5.0 
```

**Comment by idleberg** [comment]
> calling yarn fails with "'node' is not recognized as an internal or external command, operable program or batch file."

Without Node installed, you can't use make use of its package managers. Please try again using `apm install` inside the cloned folder.

**Comment by Grahamvs** [comment]
`apm install` was not working either. I ended up installing Node and using `npm` (I had to call it with the full path for it to work).

**Comment by Grahamvs** [comment]
Could I suggest adding to the readme that Node may be required if using `yarn` / `npm`, etc?

**Comment by idleberg** [comment]
I think on Windows an extra step to get `apm` and `atom` might still be necessary. I remember an *Install Shell Command* entry in the Atom menu and the command palette. I‘ll update the description, but I‘m also interested why you don‘t install packages within Atom.

**Comment by Grahamvs** [comment]
I resorted to installing it manually as after nearly 30 minutes it seemed to have gotten stuck during the installation when using Atom's built-in PM.
