### ISSUE TITLE
Uncaught TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by RedWolfIntelligence** [idleberg/atom-language-nsis#7]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [language-nsis](https://github.com/idleberg/atom-language-nsis) package 6.20.6

### Stack Trace

Uncaught TypeError: Cannot read property 'endsWith' of undefined

```
At C:\Users\user\.atom\packages\language-nsis\lib\main.js:1

TypeError: Cannot read property 'endsWith' of undefined
    at Object.compile (/packages/language-nsis/lib/main.js:1:71737)
    at /packages/language-nsis/lib/main.js:1:76797)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at Object.buildCommand (/packages/nsis-ide/lib/nsis-ide.js:1:7682)
    at /packages/nsis-ide/lib/nsis-ide.js:1:3086)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:349123)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.40.1/resources/app/static/<embedded>:11:347598)
    at ToolBarButtonView.executeCallback (/packages/tool-bar/lib/tool-bar-button-view.js:134:21)
    at ToolBarButtonView._onClick (/packages/tool-bar/lib/tool-bar-button-view.js:113:12)
```

### Commands

```
     -0:29.8.0 core:backspace (input.hidden-input)
 18x -0:29.2.0 core:move-right (input.hidden-input)
     -0:27.5.0 intentions:highlight (input.hidden-input)
     -0:26.4.0 editor:select-to-end-of-word (input.hidden-input)
     -0:25.7.0 core:backspace (input.hidden-input)
  3x -0:24.4.0 core:move-right (input.hidden-input)
     -0:24 intentions:highlight (input.hidden-input)
  4x -0:23.9.0 editor:select-to-end-of-word (input.hidden-input)
  2x -0:23.2.0 editor:select-to-beginning-of-word (input.hidden-input)
  2x -0:22.9.0 editor:select-to-end-of-word (input.hidden-input)
     -0:22.2.0 core:backspace (input.hidden-input)
     -0:19.7.0 NSIS-IDE:create-build-file (input.hidden-input)
     -0:19.6.0 NSIS:create-.atom–build-file (atom-text-editor.editor.is-focused)
     -0:13.4.0 NSIS:show-compiler-flags (input.hidden-input)
     -0:09.3.0 NSIS-IDE:compile (input.hidden-input)
     -0:09.3.0 NSIS:save-

**Comment by idleberg** [comment]
Steps to reproduce would be helpful
